# LAB 3.2 - Low level `tensorflow`

In [ ]:
!wget -nc --no-cache -O init.py -q https://raw.githubusercontent.com/rramosp/2021.deeplearning/main/content/init.py
import init; init.init(force_download=False); 

replicating local resources


In [ ]:
from local.lib.rlxmoocapi import submit, session
import inspect
session.LoginSequence(endpoint=init.endpoint, course_id=init.course_id, lab_id="L03.02", varname="student");

logging in as sebastian.restrepo9@udea.edu.co... please wait
using course session 2021.deeplearning::udea.pos.20222
success!! you are logged in


In [ ]:
import numpy as np
import os
import tensorflow as tf
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import Dense, BatchNormalization

tf.__version__

'2.9.2'

## TASK 1: Obtain layer output


**COMPLETE** the following function so that, when given a TF `model` and input  `X` returns the output of the model at layer `layer_name` when feeding `X` to the model.


You **MUST RETURN** a `numpy` array, **NOT** a tensor.

**HINT**: Use the [`tf.keras.Model`](https://www.tensorflow.org/api_docs/python/tf/keras/Model) class like in the functional API with `outputs` from the desired layer.

**CHALLENGE**: Solve it with a single line of code (not counting the `import`)

In [ ]:
def output_at_layer(X, model, layer_name):
    from tensorflow.keras.models import Model
    r = (Model(inputs=model.input, outputs=model.get_layer(layer_name).output)).predict(X)
    return r#.numpy()

check your answer manually. With the following model and weights below you should get this answer:


        >> output_at_layer(X, model, "layer_A")
        array([[0.91274303, 0.69886017, 0.8832942 ],
               [0.9311633 , 0.7634138 , 0.8924969 ],
               [0.85661894, 0.5696809 , 0.8091405 ],
               [0.8952345 , 0.6803274 , 0.8326857 ]], dtype=float32)

        >> output_at_layer(X, model, "layer_B")
        array([[0.87063193, 0.8240411 ],
               [0.8774254 , 0.83376545],
               [0.84875023, 0.7963983 ],
               [0.86286545, 0.81590414]], dtype=float32)

        >> output_at_layer(X, model, "layer_C")
        array([[0.8959839 , 0.65980244],
               [0.9032545 , 0.66435313],
               [0.8733646 , 0.646801  ],
               [0.8883195 , 0.6559416 ]], dtype=float32)

In [ ]:
def get_model(n1,n2,n3):
    model = Sequential()
    model.add(Dense(n1, name="layer_A", activation="tanh", input_dim=2))
    model.add(Dense(n2, name="layer_B", activation="sigmoid"))
    model.add(Dense(n3, name="layer_C", activation="linear"))
    return model


w = [np.array([[0.3336241 , 0.26024526, 0.37238857],
               [0.6344426 , 0.67660165, 0.31070882]], dtype=np.float32),
     np.array([0.97280777, 0.3447949 , 0.91722184], dtype=np.float32),
     
     np.array([[0.12999585, 0.31851983],
               [0.7763866 , 0.8777575 ],
               [0.99977154, 0.65771514]], dtype=np.float32),
     np.array([0.36222705, 0.05885772], dtype=np.float32),

     np.array([[0.75918376, 0.02541249],
               [0.21730722, 0.45021895]], dtype=np.float32),
     np.array([0.05594416, 0.26667854], dtype=np.float32)]


X = np.array([[0.9269997 , 0.41239464],
              [0.8461177 , 0.64935404],
              [0.27092433, 0.34251866],
              [0.22509325, 0.6301328 ]], dtype=np.float32)


model=get_model(3,2,2)
model.set_weights(w)



In [ ]:
output_at_layer(X, model, "layer_A")

1/1 [==============================] - 0s 38ms/step


array([[0.91274303, 0.69886017, 0.8832942 ],
       [0.9311633 , 0.7634138 , 0.8924969 ],
       [0.85661894, 0.5696809 , 0.8091405 ],
       [0.8952345 , 0.6803274 , 0.8326857 ]], dtype=float32)

In [ ]:
# which corresponds to a tanh activation from the input data
np.tanh(X.dot(w[0])+w[1])

array([[0.912743  , 0.69886017, 0.88329417],
       [0.9311634 , 0.7634138 , 0.89249694],
       [0.8566189 , 0.5696809 , 0.8091404 ],
       [0.89523464, 0.6803274 , 0.8326857 ]], dtype=float32)

In [ ]:
output_at_layer(X, model, "layer_B")

1/1 [==============================] - 0s 47ms/step


array([[0.87063193, 0.8240411 ],
       [0.8774253 , 0.83376545],
       [0.84875023, 0.7963982 ],
       [0.8628655 , 0.81590414]], dtype=float32)

In [ ]:
# which corresponds to a sigmoid activation from the output of layer A
sigm = lambda x: 1/(1+np.exp(-x))
sigm(output_at_layer(X, model, "layer_A").dot(w[2])+w[3])


1/1 [==============================] - 0s 38ms/step


array([[0.870632  , 0.8240412 ],
       [0.8774254 , 0.8337655 ],
       [0.8487503 , 0.7963983 ],
       [0.86286545, 0.81590414]], dtype=float32)

In [ ]:
output_at_layer(X, model, "layer_C")

1/1 [==============================] - 0s 53ms/step


array([[0.8959839 , 0.6598024 ],
       [0.90325445, 0.66435313],
       [0.8733646 , 0.646801  ],
       [0.8883195 , 0.6559416 ]], dtype=float32)

In [ ]:
# which corresponds to a linear activation from the output of layer B
output_at_layer(X, model, "layer_B").dot(w[-2])+w[-1]

1/1 [==============================] - 0s 40ms/step


array([[0.8959839 , 0.65980244],
       [0.90325445, 0.66435313],
       [0.8733646 , 0.646801  ],
       [0.8883195 , 0.6559416 ]], dtype=float32)

**Registra tu solución en linea**

In [ ]:
student.submit_task(namespace=globals(), task_id='T1');

## TASK 2: Implement batch normalization

Observe how we create a **ONE LAYER** model with **TANH** activation and batch normalization

In [ ]:
def get_model(input_dim, n):
    model = Sequential()
    model.add(Dense(n, name="layer_A", activation="tanh", input_dim=input_dim))
    model.add(BatchNormalization())
    return model    

we manually initialize it with random weights and apply it to some random input

In [ ]:
input_dim = np.random.randint(3)+2
n = np.random.randint(5)+5
X = np.random.random((6,input_dim)).astype(np.float32)
print ("input_dim", input_dim, ", n", n)

input_dim 2 , n 8


In [ ]:
model = get_model(input_dim=input_dim, n=n)
model.set_weights([np.random.random(i.shape) for i in model.get_weights()])
model(X).numpy()

array([[0.6939751 , 0.8619683 , 0.91443986, 0.54134387, 1.3640531 ,
        0.8906609 , 1.0529704 , 0.68417317],
       [0.5661464 , 0.83603513, 0.8848833 , 0.53011   , 0.8864138 ,
        0.8350307 , 0.92424566, 0.39250642],
       [0.7950077 , 0.8933056 , 0.90510553, 0.5416404 , 1.2681649 ,
        0.91957307, 1.0795405 , 0.7232526 ],
       [0.53258026, 0.82732147, 0.8803368 , 0.5274553 , 0.793789  ,
        0.82118046, 0.8937802 , 0.32214946],
       [0.5914066 , 0.8410533 , 0.89109105, 0.5328667 , 1.0017195 ,
        0.8465558 , 0.95340264, 0.46162957],
       [0.7313106 , 0.8710352 , 0.91948855, 0.5430165 , 1.4276702 ,
        0.9043704 , 1.0766197 , 0.73163414]], dtype=float32)

and we can extract the weights of the dense layer and the batch normalization layer

In [ ]:

W, b, gamma, beta, moving_mean, moving_var = model.get_weights()
W.shape, b.shape, beta.shape, moving_mean.shape, moving_var.shape


((2, 8), (8,), (8,), (8,), (8,))

**COMPLETE** the following function **WITHOUT USING TENSORFLOW** such that you get the same output as the model above, given the input and the weights.

In specific, the Dense layer output must be

$$A = \text{tanh}(XW+b)$$

And the batch normalization layer after that output is

$$\frac{A-m_\mu}{\sqrt{m_\sigma+\varepsilon}}\gamma + \beta$$

You **MUST RETURN** a `numpy` array, **NOT** a tensor.

**CHALLENGE**: Solve it with one single line of Python code.

In [ ]:
def apply_model(X, W, b, gamma, beta, moving_mean, moving_var, epsilon=1e-3):
    r = (gamma*((np.tanh(X.dot(W)+b))-moving_mean)/(np.sqrt(moving_var+epsilon)))+beta
    return r

check manually your code, the output should be the same as above.

In [ ]:
apply_model(X, W, b, gamma, beta, moving_mean, moving_var)

array([[0.6939751 , 0.8619683 , 0.9144399 , 0.54134387, 1.3640529 ,
        0.89066094, 1.0529704 , 0.6841731 ],
       [0.56614614, 0.83603513, 0.8848832 , 0.53011   , 0.8864137 ,
        0.8350307 , 0.92424566, 0.39250645],
       [0.79500765, 0.8933056 , 0.90510553, 0.5416404 , 1.2681648 ,
        0.91957307, 1.0795405 , 0.7232524 ],
       [0.53258026, 0.8273214 , 0.8803368 , 0.5274553 , 0.79378897,
        0.8211805 , 0.8937801 , 0.3221494 ],
       [0.59140646, 0.8410533 , 0.891091  , 0.5328667 , 1.0017194 ,
        0.8465558 , 0.9534025 , 0.46162948],
       [0.7313104 , 0.8710352 , 0.91948855, 0.5430165 , 1.4276702 ,
        0.9043705 , 1.0766196 , 0.7316341 ]], dtype=float32)

**Registra tu solución en linea**

In [ ]:
student.submit_task(namespace=globals(), task_id='T2');

error: ERROR EXECUTING YOUR CODE
---------------------------------
2022-10-15 21:12:25.514237: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
Traceback (most recent call last):
  File "calling_script.py", line 24, in <module>
    r = eval("nuxnqakh.{}(source_functions, source_variables, 'sebastian.restrepo9@udea.edu.co')".format(grader_function_name), namespace)
  File "<string>", line 1, in <module>
  File "/content/nuxnqakh.py", line 47, in grader_02
    t_output = model.apply(X).numpy()        
AttributeError: 'Sequential' object has no attribute 'apply'
 (set session.debug=True for tracebacks)

## TASK 3: Compute the Hessian

Complete the function below so that computes the Hessian of a function with respect to a set of variables. Remember that the Hessian is the matrix with all combinations of double partial derivatives. See [https://en.wikipedia.org/wiki/Hessian_matrix](https://en.wikipedia.org/wiki/Hessian_matrix)


The arguments for your code below:

- `expression_fn`: is a Python function that, when executed, will return a Tensor depending on the variables in `svars`.
- `svars`: a list of $n$ `tf.Variable`s against which  the derivatives are to be taken.

The result:

- a `numpy` array of dimension $n\times n$, containing in each position the value of the corresponding double derivative evaluated with the value attached to each variable in `svars`.

See the example call below to understand what you have to produce.

**NOTE**: Observe that `expression_fn` is a function that you **must call** inside some `GradientTape` to obtain the expresion. This needs to be done this way because `GradientTape` needs to _watch_ how expressions are built to be able to access the computational graph and compute the gradient. This is a technique which is very often used in Tensorflow.



**WARN**: You cannot use `tf.hessian` or `GradientTape.jacobian` or `sympy`. Do not use the name `hessian` to name any variable within your code.

**HINT 1**: use a `GradientTape` inside another `GradientTape`.

**HINT 2**: use `unconnected_gradients=tf.UnconnectedGradients.ZERO` as argument to `GradientTape.gradient` to have the variables not participating in an expresion result in gradient zero. For instance with $f=xy$, we have $\frac{\partial f}{\partial y\partial y}=0$, since $\frac{\partial f}{\partial y}=1$. Or if we have $f=x$ we have $\frac{\partial f}{\partial y\partial x}=0$, since $\frac{\partial f}{\partial y}=0$. If you do not include this argument, Tensorflow will return these values as `None` and you would have to fix them later.

In [ ]:
def get_double_derivatives(expression_fn,svars):
    import tensorflow as tf

    result = []
    
  
    for i in svars:
      columns = []
      for j in svars:
    
        with tf.GradientTape() as g:
            g.watch(i)
            g.watch(j)
    
            with tf.GradientTape() as gg:
              g.watch(i)
              g.watch(j)

              expr = expression_fn()

            derivate1 = gg.gradient(expr, i, unconnected_gradients=tf.UnconnectedGradients.ZERO)
        derivate2 = g.gradient(derivate1, j,  unconnected_gradients=tf.UnconnectedGradients.ZERO)
        
        columns.append(derivate2.numpy())
      result.append(columns) 

    result = np.array(result)
    
    return result
    

In [ ]:
x = tf.Variable(-1.0608553, dtype=tf.float32)
y = tf.Variable(-1.5622399, dtype=tf.float32)
z = tf.Variable(-1.8277323, dtype=tf.float32)
expr = lambda: 3*x**3*y**3+tf.tanh(y)*tf.sin(x)+x*tf.cos(z)*z**2

get_double_derivatives(expr, [x,y,z])

<class 'numpy.ndarray'>


array([[72.00751  , 74.23906  ,  4.1598644],
       [74.23905  , 33.314972 ,  0.       ],
       [ 4.1598644,  0.       ,  7.139834 ]], dtype=float32)

check your code. The following expression

$$f = 2xy^2 + 3x\cos{y}$$

has as first derivatives:

- $\frac{\partial f }{\partial x} = 2y^2 +3\cos{y}$
- $\frac{\partial f }{\partial y} = 4xy - 3x\sin{y}$

and as second derivatives:

- $\frac{\partial f }{\partial x \partial x} = 0$
- $\frac{\partial f }{\partial x \partial y} = 4y - 3\sin{y}$
- $\frac{\partial f }{\partial y \partial x} = 4y - 3\sin{y}$
- $\frac{\partial f }{\partial y \partial y} = 4x - 3x\cos{y}$

which, when evaluated at $x=2$ and $y=-3$ yields

    [[  0     ,  -11.58],
     [ -11.58 ,   13.94]]

In [ ]:
svars = [x,y]

resultado = []

for i in svars:
  for j in svars:
    #print(i,j)

    with tf.GradientTape() as g:
        g.watch(i)
        g.watch(j)
    
        with tf.GradientTape() as gg:
          g.watch(i)
          g.watch(j)
          expr = 2*x*y**2 + 3*x*tf.cos(y)
          
        derivate1 = gg.gradient(expr, i, unconnected_gradients=tf.UnconnectedGradients.ZERO)
    derivate2 = g.gradient(derivate1, j,  unconnected_gradients=tf.UnconnectedGradients.ZERO)
    resultado.append(derivate2.numpy())
print(resultado)

[0.0, -11.57664, -11.57664, 13.939955]


**Registra tu solución en linea**

In [ ]:
student.submit_task(namespace=globals(), task_id='T3');